import { z } from 'zod'

/**
 * Stage 4: A2A task record stored on the receiving agent's side.
 */
export const A2ATaskStatus = z.enum(['submitted', 'working', 'completed', 'failed', 'cancelled'])
export type A2ATaskStatus = z.infer<typeof A2ATaskStatus>

export const A2ATaskRecord = z.object({
  /** Unique task id (generated by receiving agent). */
  id: z.string().min(1),
  /** The peer that submitted this task. */
  senderCardId: z.string().min(1),
  /** Original task payload. */
  prompt: z.string().min(1),
  /** Optional workspace hint. */
  workspace: z.string().optional(),
  /** Optional model override. */
  model: z.string().optional(),
  /** Internal thread id created for this task. */
  threadId: z.string().optional(),
  /** Internal turn id created for this task. */
  turnId: z.string().optional(),
  status: A2ATaskStatus,
  /** Result summary (when completed). */
  summary: z.string().optional(),
  /** Error message (when failed). */
  error: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string()
}).strict()
export type A2ATaskRecord = z.infer<typeof A2ATaskRecord>
